name = "VertexModel"
uuid = "514bac63-329a-430c-b146-740bf51d96fc"
version = "0.1.0"
authors = ["chris-revell <christopher.revell@manchester.ac.uk>"]

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
AMRVW = "1.2.1"
CairoMakie = "0.15.6"
CircularArrays = "1.4.0"
ColorSchemes = "3.31.0"
Colors = "0.13.1"
Dates = "1.11.0"
DelaunayTriangulation = "1.6.4"
DiffEqCallbacks = "4.10.1"
Distributions = "0.25.122"
DrWatson = "2.19.1"
FastBroadcast = "0.3.5"
FromFile = "0.1.6"
GeometryBasics = "0.5.10"
InvertedIndices = "1.3.1"
JLD2 = "0.6.2"
LaTeXStrings = "1.4.0"
LibGit2 = "1.11.0"
LinearAlgebra = "1.12.0"
Makie = "0.24.6"
NonlinearSolve = "4.12.0"
OrdinaryDiffEq = "6.102.1"
PolynomialRoots = "1.0.0"
PrecompileTools = "1.3.3"
Printf = "1.11.0"
Random = "1.11.0"
Revise = "3.10.0"
Roots = "2.2.10"
SparseArrays = "1.12.0"
StaticArrays = "1.9.15"
StatsBase = "0.34.6"
UnPack = "1.0.2"
